# lambda expression 

# lambda expression is a anonymous function that can take any number of arguments, but can only have one expression. It is used to create small, one-time, and inline functions in Python.

def addition(a, b): 
    return a + b

print(addition(2, 3)) # it will return 5 because it is the sum of 2 and 3

addition_lambda = lambda a,b: a + b # it will create a lambda function that takes two arguments a and b and returns their sum
print(addition_lambda(2,3)) # it will return 5 because it is the sum of 2 and 3

# Map function
# Map function is a built-in function in Python that takes a function and an iterable as arguments and returns a map object which is an iterator that applies the function to every item of the iterable.

a =  [1,2,3,4]

l = []

for i in a: 
    l.append(i*2) # it will append the double of each element in the list a to the list l

print(l) # it will print [2, 4, 6, 8] because it is the double of each element in the list a

# using map function to achieve the same result as above
l = list(map(lambda x: x*2, a)) # it will create a map object that applies the lambda function to each element in the list a and then converts it to a list
print(l) # it will print [2, 4, 6, 8]

def square(x): 
    return x**2

l = list(map(square, a))

# filter function

# Filter function is a built-in function in Python that takes a function and an iterable as arguments and returns a filter object which is an iterator that filters the items of the iterable based on the function.

n = [1,2,3,4,5,6]

l = list(filter(lambda x: x % 2 == 0, n)) # it will create a filter object that applies the lambda function to each element in the list n and returns only the even numbers
print(l) # it will print [2, 4, 6] because they are the even numbers in the list n

# zip function
# Zip function is a built-in function in Python that takes two or more iterables as arguments and returns an iterator of tuples where the i-th tuple contains the i-th element from each of the argument sequences or iterables.

name = ["omer", "aayan", "ali"]

ages = [20, 21, 22]

address = ["123 street", "456 street", "789 street"]

zipped = zip(name, ages, address) # it will create a zip object that combines the elements of the name, ages, and address lists into tuples

print(list(zipped)) # it will print [('omer', 20, '123 street'), ('aayan', 21, '456 street'), ('ali', 22, '789 street')] because it combines the elements of the three lists into tuples

# list comprehension
# List comprehension is a concise way to create lists in Python. It consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The expressions can be anything, meaning you can put in all kinds of objects in lists.

a  = [1,2,3,4,5,6,7,8]
l = [i*2 for i in a] # it will create a new list that contains the double of each element in the list a
print(l) # it will print [2, 4, 6, 8, 10, 12, 14, 16] because it is the double of each element

l = {i for i in a if i % 2 == 0} # it will create a new set that contains only the even numbers from the list a
print(l) # it will print {2, 4, 6, 8} because they are the even numbers in the list a

l = {i: i**2 for i in a if i % 2 == 0} # it will create a new dictionary that contains the even numbers from the list a as keys and their squares as values
print(l) # it will print {2: 4, 4: 16, 6: 36, 8: 64} because it contains the even numbers from the list a as keys and their squares as values

# generator expression
# Generator expression is a concise way to create generators in Python. It is similar to list comprehension but it uses parentheses instead of brackets. It returns a generator object which can be iterated over to get the values one at a time.

def my_generator(): 
    for i in range(5): 
        yield i 

print(my_generator()) # it will return a generator object because it is the first value returned by the generator function but it will not print the values because we are not iterating over the generator object

gen = my_generator() # it will create a generator object that can be iterated over to get the values one at a time
print(next(gen)) # it will print 0 because it is the first value returned by the generator function
print(next(gen)) # it will print 1 because it is the second value returned by the generator function
print(list(gen)) # it will print [2, 3, 4] because it is the remaining values returned by the generator function after we have already called next() twice to get the first two values

# generator sequence
sequence = (x**2 for x in range(5)) # it will create a generator object that generates the squares of the numbers from 0 to 4
print(next(sequence)) # it will print 0 because it is the first value generated by the generator expression
print(next(sequence)) # it will print 1 because it is the second value generated by the generator expression
print(list(sequence)) # it will print [4, 9, 16] because it is the remaining values generated by the generator expression after we have already called next() twice to get the first two values

# decorators
# Decorators are a powerful and useful tool in Python that allows you to modify the behavior of a function or a class. They are functions that take another function as an argument and return a new function that is a modified version of the original function.

def my_decorator(func):
    def wrapper(): 
        print("Before the function is called") # it will print this message before calling the original function
        func() # it will call the original function
        print("After the function is called") # it will print this message after calling the original function
    return wrapper # it will return the wrapper function which is a modified version of the original function

@my_decorator
def say_hello():
    print("Hello!")

say_hello() # it will print "Hello!" because it is the original function that we defined